### ISSUE TITLE
Some more errors

### ISSUE THREAD

**Issue by pieterhouwen** [Cignoraptor-ita/cignotrack#2]
I ran the program against my own website and came across these errors (whois worked fine).
Am I missing some dependencies?

`
Searching pdf files...
--2017-08-01 16:41:18--  http://google.com/search?q=site:pieterhouwen.info+filetype:pdf
Resolving google.com (google.com)... 172.217.17.142, 2a00:1450:400e:807::200e
Connecting to google.com (google.com)|172.217.17.142|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.google.nl/search?q=site:pieterhouwen.info+filetype:pdf&gws_rd=cr&ei=cOeAWfePJMHWwAKZw7-QCA [following]
--2017-08-01 16:41:18--  http://www.google.nl/search?q=site:pieterhouwen.info+filetype:pdf&gws_rd=cr&ei=cOeAWfePJMHWwAKZw7-QCA
Resolving www.google.nl (www.google.nl)... 108.177.119.94, 2a00:1450:4013:c00::5e
Connecting to www.google.nl (www.google.nl)|108.177.119.94|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.google.nl/search?q=site:pieterhouwen.info+filetype:pdf&gws_rd=cr,ssl&ei=cOeAWfePJMHWwAKZw7-QCA [following]
--2017-08-01 16:41:18--  https://www.google.nl/search?q=site:pieterhouwen.info+filetype:pdf&gws_rd=cr,ssl&ei=cOeAWfePJMHWwAKZw7-QCA
Connecting to www.google.nl (www.google.nl)|108.177.119.94|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘analysis/search?q=site:pieterhouwen.info+filetype:pdf’

search?q=site:pieterhouwen.info+filet     [  <=>                                                                  ] 261.07K  1.20MB/s    in 0.2s    

2017-08-01 16:41:19 (1.20 MB/s) - ‘analysis/search?q=site:pieterhouwen.info+filetype:pdf’ saved [267340]

FINISHED --2017-08-01 16:41:19--
Total wall clock time: 0.8s
Downloaded: 1 files, 261K in 0.2s (1.20 MB/s)
 
METADATA EXTRACTION...
 
=============================
============================= 
============================= 
=============================
============================= 
============================= 
============================= 
 
Converting pdf files in txt and IP/EMAIL analysis
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error (2): Illegal character <21> in hex string
Syntax Error (4): Illegal character <6f> in hex string
Syntax Error (6): Illegal character <74> in hex string
Syntax Error (7): Illegal character <79> in hex string
Syntax Error (8): Illegal character <70> in hex string
Syntax Error (11): Illegal character <68> in hex string
Syntax Error (12): Illegal character <74> in hex string
Syntax Error (13): Illegal character <6d> in hex string
Syntax Error (14): Illegal character <6c> in hex string
Syntax Error (17): Illegal character <68> in hex string
Syntax Error (18): Illegal character <74> in hex string
Syntax Error (19): Illegal character <6d> in hex string
Syntax Error (20): Illegal character <6c> in hex string
Syntax Error (22): Illegal character <69> in hex string
Syntax Error (23): Illegal character <74> in hex string
Syntax Error (25): Illegal character <6d> in hex string
Syntax Error (26): Illegal character <73> in hex string
Syntax Error (28): Illegal character <6f> in hex string
Syntax Error (29): Illegal character <70> in hex string
Syntax Error (31): Illegal character <3d> in hex string
Syntax Error (32): Illegal character <22> in hex string
Syntax Error (33): Illegal character <22> in hex string
Syntax Error (35): Illegal character <69> in hex string
Syntax Error (36): Illegal character <74> in hex string
Syntax Error (38): Illegal character <6d> in hex string
Syntax Error (39): Illegal character <74> in hex string
Syntax Error (40): Illegal character <79> in hex string
Syntax Error (41): Illegal character <70> in hex string
Syntax Error (43): Illegal character <3d> in hex string
Syntax Error (44): Illegal character <22> in hex string
Syntax Error (45): Illegal character <68> in hex string
Syntax Error (46): Illegal character <74> in hex string
Syntax Error (47): Illegal character <74> in hex string
Syntax Error (48): Illegal character <70> in hex string
Syntax Error (49): Illegal character <3a> in hex string
Syntax Error (50): Illegal character <2f> in hex string
Syntax Error (51): Illegal character <2f> in hex string
Syntax Error (52): Illegal character <73> in hex string
Syntax Error (54): Illegal character <68> in hex string
Syntax Error (56): Illegal character <6d> in hex string
Syntax Error (58): Illegal character <2e> in hex string
Syntax Error (59): Illegal character <6f> in hex string
Syntax Error (60): Illegal character <72> in hex string
Syntax Error (61): Illegal character <67> in hex string
Syntax Error (62): Illegal character <2f> in hex string
Syntax Error (63): Illegal character <53> in hex string
Syntax Error (66): Illegal character <72> in hex string
Syntax Error (68): Illegal character <68> in hex string
Syntax Error (69): Illegal character <52> in hex string
Syntax Error (71): Illegal character <73> in hex string
Syntax Error (72): Illegal character <75> in hex string
Syntax Error (73): Illegal character <6c> in hex string
Syntax Error (74): Illegal character <74> in hex string
Syntax Error (75): Illegal character <73> in hex string
Syntax Error (76): Illegal character <50> in hex string
Syntax Error (78): Illegal character <67> in hex string
Syntax Error (80): Illegal character <22> in hex string
Syntax Error (82): Illegal character <6c> in hex string
Syntax Error (84): Illegal character <6e> in hex string
Syntax Error (85): Illegal character <67> in hex string
Syntax Error (86): Illegal character <3d> in hex string
Syntax Error (87): Illegal character <22> in hex string
Syntax Error (88): Illegal character <6e> in hex string
Syntax Error (89): Illegal character <6c> in hex string
Syntax Error (90): Illegal character <22> in hex string
Syntax Error (93): Illegal character <68> in hex string
Syntax Error (99): Illegal character <6d> in hex string
Syntax Error (101): Illegal character <74> in hex string
Syntax Error (105): Illegal character <6f> in hex string
Syntax Error (106): Illegal character <6e> in hex string
Syntax Error (107): Illegal character <74> in hex string
Syntax Error (109): Illegal character <6e> in hex string
Syntax Error (110): Illegal character <74> in hex string
Syntax Error (111): Illegal character <3d> in hex string
Syntax Error (112): Illegal character <22> in hex string
Syntax Error (113): Illegal character <2f> in hex string
Syntax Error (114): Illegal character <69> in hex string
Syntax Error (115): Illegal character <6d> in hex string
Syntax Error (117): Illegal character <67> in hex string
Syntax Error (119): Illegal character <73> in hex string
Syntax Error (120): Illegal character <2f> in hex string
Syntax Error (122): Illegal character <72> in hex string
Syntax Error (124): Illegal character <6e> in hex string
Syntax Error (126): Illegal character <69> in hex string
Syntax Error (127): Illegal character <6e> in hex string
Syntax Error (128): Illegal character <67> in hex string
Syntax Error (129): Illegal character <2f> in hex string
Syntax Error (130): Illegal character <67> in hex string
Syntax Error (131): Illegal character <6f> in hex string
Syntax Error (132): Illegal character <6f> in hex string
Syntax Error (133): Illegal character <67> in hex string
Syntax Error (134): Illegal character <6c> in hex string
Syntax Error (136): Illegal character <67> in hex string
Syntax Error (137): Illegal character <2f> in hex string
Syntax Error (139): Illegal character <78> in hex string
Syntax Error (140): Illegal character <2f> in hex string
Syntax Error (141): Illegal character <67> in hex string
Syntax Error (142): Illegal character <6f> in hex string
Syntax Error (143): Illegal character <6f> in hex string
Syntax Error (144): Illegal character <67> in hex string
Syntax Error (145): Illegal character <6c> in hex string
Syntax Error (147): Illegal character <67> in hex string
Syntax Error (148): Illegal character <5f> in hex string
Syntax Error (149): Illegal character <73> in hex string
Syntax Error (150): Illegal character <74> in hex string
Syntax Error (152): Illegal character <6e> in hex string
Syntax Error (155): Illegal character <72> in hex string
Syntax Error (157): Illegal character <5f> in hex string
Syntax Error (159): Illegal character <6f> in hex string
Syntax Error (160): Illegal character <6c> in hex string
Syntax Error (161): Illegal character <6f> in hex string
Syntax Error (162): Illegal character <72> in hex string
Syntax Error (163): Illegal character <5f> in hex string
Syntax Error (168): Illegal character <70> in hex string
Syntax Error (169): Illegal character <2e> in hex string
Syntax Error (170): Illegal character <70> in hex string
Syntax Error (171): Illegal character <6e> in hex string
Syntax Error (172): Illegal character <67> in hex string
Syntax Error (173): Illegal character <22> in hex string
Syntax Error (175): Illegal character <69> in hex string
Syntax Error (176): Illegal character <74> in hex string
Syntax Error (178): Illegal character <6d> in hex string
Syntax Error (179): Illegal character <70> in hex string
Syntax Error (180): Illegal character <72> in hex string
Syntax Error (181): Illegal character <6f> in hex string
Syntax Error (182): Illegal character <70> in hex string
Syntax Error (183): Illegal character <3d> in hex string
Syntax Error (184): Illegal character <22> in hex string
Syntax Error (185): Illegal character <69> in hex string
Syntax Error (186): Illegal character <6d> in hex string
Syntax Error (188): Illegal character <67> in hex string
Syntax Error (190): Illegal character <22> in hex string
Syntax Error (193): Illegal character <6c> in hex string
Syntax Error (194): Illegal character <69> in hex string
Syntax Error (195): Illegal character <6e> in hex string
Syntax Error (196): Illegal character <6b> in hex string
Syntax Error (198): Illegal character <68> in hex string
Syntax Error (199): Illegal character <72> in hex string
Syntax Error (202): Illegal character <3d> in hex string
Syntax Error (203): Illegal character <22> in hex string
Syntax Error (204): Illegal character <2f> in hex string
Syntax Error (205): Illegal character <69> in hex string
Syntax Error (206): Illegal character <6d> in hex string
Syntax Error (208): Illegal character <67> in hex string
Syntax Error (210): Illegal character <73> in hex string
Syntax Error (211): Illegal character <2f> in hex string
Syntax Error (213): Illegal character <72> in hex string
Syntax Error (215): Illegal character <6e> in hex string
Syntax Error (217): Illegal character <69> in hex string
Syntax Error (218): Illegal character <6e> in hex string
Syntax Error (219): Illegal character <67> in hex string
Syntax Error (220): Illegal character <2f> in hex string
Syntax Error (221): Illegal character <70> in hex string
Syntax Error (222): Illegal character <72> in hex string
Syntax Error (223): Illegal character <6f> in hex string
Syntax Error (225): Illegal character <75> in hex string
Syntax Error (227): Illegal character <74> in hex string
Syntax Error (228): Illegal character <2f> in hex string
Syntax Error (229): Illegal character <69> in hex string
Syntax Error (231): Illegal character <6f> in hex string
Syntax Error (232): Illegal character <2f> in hex string
Syntax Error (233): Illegal character <67> in hex string
Syntax Error (234): Illegal character <6f> in hex string
Syntax Error (235): Illegal character <6f> in hex string
Syntax Error (236): Illegal character <67> in hex string
Syntax Error (237): Illegal character <6c> in hex string
Syntax Error (239): Illegal character <67> in hex string
Syntax Error (240): Illegal character <5f> in hex string
Syntax Error (241): Illegal character <6c> in hex string
Syntax Error (242): Illegal character <6f> in hex string
Syntax Error (244): Illegal character <70> in hex string
Syntax Error (245): Illegal character <2e> in hex string
Syntax Error (246): Illegal character <69> in hex string
Syntax Error (248): Illegal character <6f> in hex string
Syntax Error (249): Illegal character <22> in hex string
Syntax Error (251): Illegal character <72> in hex string
Syntax Error (253): Illegal character <6c> in hex string
Syntax Error (254): Illegal character <3d> in hex string
Syntax Error (255): Illegal character <22> in hex string
Syntax Error (256): Illegal character <73> in hex string
Syntax Error (257): Illegal character <68> in hex string
Syntax Error (258): Illegal character <6f> in hex string
Syntax Error (259): Illegal character <72> in hex string
Syntax Error (260): Illegal character <74> in hex string
Syntax Error (262): Illegal character <75> in hex string
Syntax Error (263): Illegal character <74> in hex string
Syntax Error (265): Illegal character <69> in hex string
Syntax Error (267): Illegal character <6f> in hex string
Syntax Error (268): Illegal character <6e> in hex string
Syntax Error (269): Illegal character <22> in hex string
Syntax Error (272): Illegal character <74> in hex string
Syntax Error (273): Illegal character <69> in hex string
Syntax Error (274): Illegal character <74> in hex string
Syntax Error (275): Illegal character <6c> in hex string
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error (2): Illegal character <21> in hex string
Syntax Error (4): Illegal character <6f> in hex string
Syntax Error (6): Illegal character <74> in hex string
Syntax Error (7): Illegal character <79> in hex string
Syntax Error (8): Illegal character <70> in hex string
Syntax Error (11): Illegal character <68> in hex string
Syntax Error (12): Illegal character <74> in hex string
Syntax Error (13): Illegal character <6d> in hex string
Syntax Error (14): Illegal character <6c> in hex string
Syntax Error (17): Illegal character <68> in hex string
Syntax Error (18): Illegal character <74> in hex string
Syntax Error (19): Illegal character <6d> in hex string
Syntax Error (20): Illegal character <6c> in hex string
Syntax Error (22): Illegal character <69> in hex string
Syntax Error (23): Illegal character <74> in hex string
Syntax Error (25): Illegal character <6d> in hex string
Syntax Error (26): Illegal character <73> in hex string
Syntax Error (28): Illegal character <6f> in hex string
Syntax Error (29): Illegal character <70> in hex string
Syntax Error (31): Illegal character <3d> in hex string
Syntax Error (32): Illegal character <22> in hex string
Syntax Error (33): Illegal character <22> in hex string
Syntax Error (35): Illegal character <69> in hex string
Syntax Error (36): Illegal character <74> in hex string
Syntax Error (38): Illegal character <6d> in hex string
Syntax Error (39): Illegal character <74> in hex string
Syntax Error (40): Illegal character <79> in hex string
Syntax Error (41): Illegal character <70> in hex string
Syntax Error (43): Illegal character <3d> in hex string
Syntax Error (44): Illegal character <22> in hex string
Syntax Error (45): Illegal character <68> in hex string
Syntax Error (46): Illegal character <74> in hex string
Syntax Error (47): Illegal character <74> in hex string
Syntax Error (48): Illegal character <70> in hex string
Syntax Error (49): Illegal character <3a> in hex string
Syntax Error (50): Illegal character <2f> in hex string
Syntax Error (51): Illegal character <2f> in hex string
Syntax Error (52): Illegal character <73> in hex string
Syntax Error (54): Illegal character <68> in hex string
Syntax Error (56): Illegal character <6d> in hex string
Syntax Error (58): Illegal character <2e> in hex string
Syntax Error (59): Illegal character <6f> in hex string
Syntax Error (60): Illegal character <72> in hex string
Syntax Error (61): Illegal character <67> in hex string
Syntax Error (62): Illegal character <2f> in hex string
Syntax Error (63): Illegal character <53> in hex string
Syntax Error (66): Illegal character <72> in hex string
Syntax Error (68): Illegal character <68> in hex string
Syntax Error (69): Illegal character <52> in hex string
Syntax Error (71): Illegal character <73> in hex string
Syntax Error (72): Illegal character <75> in hex string
Syntax Error (73): Illegal character <6c> in hex string
Syntax Error (74): Illegal character <74> in hex string
Syntax Error (75): Illegal character <73> in hex string
Syntax Error (76): Illegal character <50> in hex string
Syntax Error (78): Illegal character <67> in hex string
Syntax Error (80): Illegal character <22> in hex string
Syntax Error (82): Illegal character <6c> in hex string
Syntax Error (84): Illegal character <6e> in hex string
Syntax Error (85): Illegal character <67> in hex string
Syntax Error (86): Illegal character <3d> in hex string
Syntax Error (87): Illegal character <22> in hex string
Syntax Error (88): Illegal character <6e> in hex string
Syntax Error (89): Illegal character <6c> in hex string
Syntax Error (90): Illegal character <22> in hex string
Syntax Error (93): Illegal character <68> in hex string
Syntax Error (99): Illegal character <6d> in hex string
Syntax Error (101): Illegal character <74> in hex string
Syntax Error (105): Illegal character <6f> in hex string
Syntax Error (106): Illegal character <6e> in hex string
Syntax Error (107): Illegal character <74> in hex string
Syntax Error (109): Illegal character <6e> in hex string
Syntax Error (110): Illegal character <74> in hex string
Syntax Error (111): Illegal character <3d> in hex string
Syntax Error (112): Illegal character <22> in hex string
Syntax Error (113): Illegal character <2f> in hex string
Syntax Error (114): Illegal character <69> in hex string
Syntax Error (115): Illegal character <6d> in hex string
Syntax Error (117): Illegal character <67> in hex string
Syntax Error (119): Illegal character <73> in hex string
Syntax Error (120): Illegal character <2f> in hex string
Syntax Error (122): Illegal character <72> in hex string
Syntax Error (124): Illegal character <6e> in hex string
Syntax Error (126): Illegal character <69> in hex string
Syntax Error (127): Illegal character <6e> in hex string
Syntax Error (128): Illegal character <67> in hex string
Syntax Error (129): Illegal character <2f> in hex string
Syntax Error (130): Illegal character <67> in hex string
Syntax Error (131): Illegal character <6f> in hex string
Syntax Error (132): Illegal character <6f> in hex string
Syntax Error (133): Illegal character <67> in hex string
Syntax Error (134): Illegal character <6c> in hex string
Syntax Error (136): Illegal character <67> in hex string
Syntax Error (137): Illegal character <2f> in hex string
Syntax Error (139): Illegal character <78> in hex string
Syntax Error (140): Illegal character <2f> in hex string
Syntax Error (141): Illegal character <67> in hex string
Syntax Error (142): Illegal character <6f> in hex string
Syntax Error (143): Illegal character <6f> in hex string
Syntax Error (144): Illegal character <67> in hex string
Syntax Error (145): Illegal character <6c> in hex string
Syntax Error (147): Illegal character <67> in hex string
Syntax Error (148): Illegal character <5f> in hex string
Syntax Error (149): Illegal character <73> in hex string
Syntax Error (150): Illegal character <74> in hex string
Syntax Error (152): Illegal character <6e> in hex string
Syntax Error (155): Illegal character <72> in hex string
Syntax Error (157): Illegal character <5f> in hex string
Syntax Error (159): Illegal character <6f> in hex string
Syntax Error (160): Illegal character <6c> in hex string
Syntax Error (161): Illegal character <6f> in hex string
Syntax Error (162): Illegal character <72> in hex string
Syntax Error (163): Illegal character <5f> in hex string
Syntax Error (168): Illegal character <70> in hex string
Syntax Error (169): Illegal character <2e> in hex string
Syntax Error (170): Illegal character <70> in hex string
Syntax Error (171): Illegal character <6e> in hex string
Syntax Error (172): Illegal character <67> in hex string
Syntax Error (173): Illegal character <22> in hex string
Syntax Error (175): Illegal character <69> in hex string
Syntax Error (176): Illegal character <74> in hex string
Syntax Error (178): Illegal character <6d> in hex string
Syntax Error (179): Illegal character <70> in hex string
Syntax Error (180): Illegal character <72> in hex string
Syntax Error (181): Illegal character <6f> in hex string
Syntax Error (182): Illegal character <70> in hex string
Syntax Error (183): Illegal character <3d> in hex string
Syntax Error (184): Illegal character <22> in hex string
Syntax Error (185): Illegal character <69> in hex string
Syntax Error (186): Illegal character <6d> in hex string
Syntax Error (188): Illegal character <67> in hex string
Syntax Error (190): Illegal character <22> in hex string
Syntax Error (193): Illegal character <6c> in hex string
Syntax Error (194): Illegal character <69> in hex string
Syntax Error (195): Illegal character <6e> in hex string
Syntax Error (196): Illegal character <6b> in hex string
Syntax Error (198): Illegal character <68> in hex string
Syntax Error (199): Illegal character <72> in hex string
Syntax Error (202): Illegal character <3d> in hex string
Syntax Error (203): Illegal character <22> in hex string
Syntax Error (204): Illegal character <2f> in hex string
Syntax Error (205): Illegal character <69> in hex string
Syntax Error (206): Illegal character <6d> in hex string
Syntax Error (208): Illegal character <67> in hex string
Syntax Error (210): Illegal character <73> in hex string
Syntax Error (211): Illegal character <2f> in hex string
Syntax Error (213): Illegal character <72> in hex string
Syntax Error (215): Illegal character <6e> in hex string
Syntax Error (217): Illegal character <69> in hex string
Syntax Error (218): Illegal character <6e> in hex string
Syntax Error (219): Illegal character <67> in hex string
Syntax Error (220): Illegal character <2f> in hex string
Syntax Error (221): Illegal character <70> in hex string
Syntax Error (222): Illegal character <72> in hex string
Syntax Error (223): Illegal character <6f> in hex string
Syntax Error (225): Illegal character <75> in hex string
Syntax Error (227): Illegal character <74> in hex string
Syntax Error (228): Illegal character <2f> in hex string
Syntax Error (229): Illegal character <69> in hex string
Syntax Error (231): Illegal character <6f> in hex string
Syntax Error (232): Illegal character <2f> in hex string
Syntax Error (233): Illegal character <67> in hex string
Syntax Error (234): Illegal character <6f> in hex string
Syntax Error (235): Illegal character <6f> in hex string
Syntax Error (236): Illegal character <67> in hex string
Syntax Error (237): Illegal character <6c> in hex string
Syntax Error (239): Illegal character <67> in hex string
Syntax Error (240): Illegal character <5f> in hex string
Syntax Error (241): Illegal character <6c> in hex string
Syntax Error (242): Illegal character <6f> in hex string
Syntax Error (244): Illegal character <70> in hex string
Syntax Error (245): Illegal character <2e> in hex string
Syntax Error (246): Illegal character <69> in hex string
Syntax Error (248): Illegal character <6f> in hex string
Syntax Error (249): Illegal character <22> in hex string
Syntax Error (251): Illegal character <72> in hex string
Syntax Error (253): Illegal character <6c> in hex string
Syntax Error (254): Illegal character <3d> in hex string
Syntax Error (255): Illegal character <22> in hex string
Syntax Error (256): Illegal character <73> in hex string
Syntax Error (257): Illegal character <68> in hex string
Syntax Error (258): Illegal character <6f> in hex string
Syntax Error (259): Illegal character <72> in hex string
Syntax Error (260): Illegal character <74> in hex string
Syntax Error (262): Illegal character <75> in hex string
Syntax Error (263): Illegal character <74> in hex string
Syntax Error (265): Illegal character <69> in hex string
Syntax Error (267): Illegal character <6f> in hex string
Syntax Error (268): Illegal character <6e> in hex string
Syntax Error (269): Illegal character <22> in hex string
Syntax Error (272): Illegal character <74> in hex string
Syntax Error (273): Illegal character <69> in hex string
Syntax Error (274): Illegal character <74> in hex string
Syntax Error (275): Illegal character <6c> in hex string
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

web screenshot
Loading page (1/2)
QSslSocket: cannot resolve CRYPTO_num_locks                  ] 10%
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
QSslSocket: cannot call unresolved function SSLv23_client_method4%
QSslSocket: cannot call unresolved function SSL_library_init
Warning: Failed to load https://ssl.gstatic.com/gb/images/b_8d5afc09.png (ignore)
Rendering (2/2)                                                    
Done                                                               
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback

root@supersecretkali:/opt/intelligence-gathering/cignotrack# ls
analysis  cignotrack.sh  README.md  target.png
root@supersecretkali:/opt/intelligence-gathering/cignotrack# cd analysis/
root@supersecretkali:/opt/intelligence-gathering/cignotrack/analysis# ls
search?q=site:pieterhouwen.info+filetype:pdf 
root@supersecretkali:/opt/intelligence-gathering/cignotrack/analysis# file search\?q\=site\:pieterhouwen.info+filetype\:pdf 
search?q=site:pieterhouwen.info+filetype:pdf: HTML document, UTF-8 Unicode text, with very long lines
root@supersecretkali:/opt/intelligence-gathering/cignotrack/analysis# 

`

**Comment by Cignoraptor-ita** [comment]
Try new version, Real swan. Now seems no problem for me. 
Ensure to install all the necessary and tell me if you have problems.
Best regards.

**Comment by pieterhouwen** [comment]
Alright, now it goes better for me, though I'm not sure what the file in /analysis is for (it's just a HTML document). 

There are some other things: when it comes to Social media links it sees that my site is HTTPS only, it makes a connection and then tries something with lynx, but lynx goes to the http version (which fails). I'm not sure what that's for but thought you may want to know. (error message is "can't access startfile http://pieterhouwen.info).  Same goes for email spider, and top 20 words. 


The web screenshot however now gives another error:
QSslSocket: cannot resolve SSLv3_client_method
and
QSslSocket: cannot resolve SSLv3_server_method

Also the METADATA EXTRACTION just gives me a block of = signs and then states the directory from which it was executed, don't think that should happen.

Cheers,
Pieter

**Comment by Cignoraptor-ita** [comment]
Hi, Lynx have problems with some https websites, it offers no ECDHE ciphers and the handshake fail. Now i tried with wget and the ignore certificate option for a better compatibility for more websites.
The web screenshot it is provided by wkhtmltopdf and have itself  problems with some SSL certificates like Lynx and for the moment i don t have found a valid substitute or a better compatibility fix. 
Anyway, try new version "Frozen Swan" it seems works better in more websites.

Thanks for the infos.
Best regards.

**Comment by Cignoraptor-ita** [comment]
Try new version "Swan in the lake".

**Comment by pieterhouwen** [comment]
I ran the tool with the following results:

 [output omitted]
PDF ANALYSIS IS SUSPENDED FOR THE MOMENT
Both --no-clobber and --convert-links were specified, only --convert-links will be used.
--2017-09-27 05:09:54--  http://pieterhouwen.info/
Resolving pieterhouwen.info (pieterhouwen.info)... 185.182.57.114, 2a0b:7280:300:0:433:64ff:fe00:2367
Connecting to pieterhouwen.info (pieterhouwen.info)|185.182.57.114|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://pieterhouwen.info/ [following]
--2017-09-27 05:09:56--  https://pieterhouwen.info/
Connecting to pieterhouwen.info (pieterhouwen.info)|185.182.57.114|:443... connected.
ERROR: The certificate of ‘pieterhouwen.info’ is not trusted.
ERROR: The certificate of ‘pieterhouwen.info’ hasn't got a known issuer.
ERROR: The certificate of ‘pieterhouwen.info’ was signed using an insecure algorithm.
Converted links in 0 files in 0 seconds.
 
METADATA EXTRACTION...
 
Artist...
File not found: *
=============================
Software...
File not found: *
============================= 
Make...
File not found: *
============================= 
Author...
File not found: *
=============================
Creator...
File not found: *
============GPS LATITUDE=================
File not found: *
============GPS LONGITUDE=================
File not found: *
 
/opt/intelligence-gathering/cignotrack
 
pieterhouwen.info Searching in FACEBOOK
 
         Nederland  https://nl-nl.facebook.com/public/Pieter-Houwen             
         uur        https://nl-nl.facebook.com/pieter.houwen                    
  *    * Alle       https://www.facebook.com/public/Pieter-Houwen               
                    https://nl-nl.facebook.com/.../Pieter-Houwen/.../Veldhoven- 
                    https://nl-nl.facebook.com/public/Piet-Houwen               
                    https://www.facebook.com/pieter.houwen                      
                    https://www.facebook.com/INGnl/?nr                          
                    https://sv-se.facebook.com/CTWT.NL/                         
                    https://de-de.facebook.com/haagse.komputerhulp              
                    https://fr-fr.facebook.com/CTWT.NL/?rc=p                    
  *    * Alle       https://www.facebook.com/public/Pieter-Houwen               
                    https://www.facebook.com/pieter.houwen                      
                    https://www.facebook.com/INGnl/?nr                          
                    image. www.ctwt.nl.                                         
                        Adv.www.csv-networks.nl/                                
                        Adv.www.futureweb.be/domain                             
 
Some Linkedin people links associated with organization target
         Nederland  https://nl.linkedin.com/in/pieterhouwen                                   
       * Afgelopen  https://nl.linkedin.com/pub/dir/Pieter/Houwen                             
         jaar       https://nl.linkedin.com/in/pieter-houwen-1a7b0213                         
                    https://www.linkedin.com/pub/dir/Pieter/Houwen                            
                    https://nl.linkedin.com/in/pieter-houwen-47761b101                        
                    https://nl.linkedin.com/.../Pieter/Houwen/nl-5688-Den-Haag-en-omgeving,-  
                    https://be.linkedin.com/in/pieter-houwen-47311266                         
                    https://nl.linkedin.com/in/hansdemare                                     
                    https://nl.linkedin.com/.../Pieter/Houwen/nl-5664-Amsterdam-en-omgeving,- 
                    https://nl.linkedin.com/in/ger-van-lieshout-b3b56063                      
                    https://www.linkedin.com/pub/dir/Pieter/Houwen                            
 
Web screenshot
Loading page (1/2)
QSslSocket: cannot resolve SSLv3_client_method               ] 10%
QSslSocket: cannot resolve SSLv3_server_method
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/css/bootstrap.css (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/css/font-awesome.css (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/css/animate.css (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/css/theme.css (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/js/jquery.js (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/js/modernizr.js (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/js/menustick.js (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/js/smoothscroll.js (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/js/masonry.js (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/js/imgloaded.js (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/js/colorfinder.js (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/js/gridscroll.js (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/img/1.jpg (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/img/2.jpg (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/img/toetsenbord.jpg (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/img/windows.png (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/img/security.png (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/img/network-scanner-logo.png (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/img/powershell.png (ignore)
Warning: Failed to load file:///opt/intelligence-gathering/cignotrack/img/help.jpg (ignore)
Warning: SSL error ignored
Warning: SSL error ignored
Rendering (2/2)                                                    
Done                                                               
Exit with code 1 due to network error: ContentNotFoundError

Email enumeration found my email address but also alot of gibberish

**Comment by Cignoraptor-ita** [comment]
Thanks for the report, try new version "Elite swan" with email and documents search rewrited.

**Comment by pieterhouwen** [comment]
Thanks for getting back, it works wonderfully now!
